services:
  db:
    image: postgres:15
    container_name: barbershop-db
    restart: always
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:7-alpine"
    container_name: barbershop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: barbershop-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/barbershop
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
      gunicorn src.app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: barbershop-celery-worker
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/barbershop
      REDIS_URL: redis://redis:6379/0
    command: celery -A src.app.celery_worker.celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  pg_data:
  redis_data:
