services:
  db:
    image: postgres:15
    container_name: barbershop-db
    restart: always
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: "redis:7-alpine"
    container_name: barbershop-redis
    restart: always
    ports:
      - "6379:6379"


volumes:
  pg_data:
  redis_data:
