"""Add user_id and timestamps to appointments

Revision ID: 23f1797b566a
Revises: 68470bfddc71
Create Date: 2025-06-03 21:36:11.626773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f1797b566a'
down_revision: Union[str, None] = '68470bfddc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('scheduled_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key('fk_appointments_user_id_users', 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_user_id_users', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'scheduled_time')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
