"""Add status to Appointment with default

Revision ID: a6d0a5726ea7
Revises: cec6d406558e
Create Date: 2025-06-25 12:46:23.455861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d0a5726ea7'
down_revision: Union[str, None] = 'cec6d406558e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.Enum('upcoming', 'completed', 'cancelled', name='appointmentstatus'), server_default='upcoming', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
