"""Add scheduled_end column to appointments

Revision ID: ab5a81696f90
Revises: a6d0a5726ea7
Create Date: 2025-07-07 13:39:08.869495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5a81696f90'
down_revision: Union[str, None] = 'a6d0a5726ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "appointments",
        sa.Column(
            "scheduled_end",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()")
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'scheduled_end')
    # ### end Alembic commands ###
