"""Add FK to barber_id and service_id

Revision ID: ba8973cb55f5
Revises: 23f1797b566a
Create Date: 2025-06-04 00:38:23.533935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8973cb55f5'
down_revision: Union[str, None] = '23f1797b566a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_appointments_barber_id', 'appointments', 'barbers', ['barber_id'], ['id'])
    op.create_foreign_key('fk_appointments_service_id', 'appointments', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_barber_id', 'appointments', type_='foreignkey')
    op.drop_constraint('fk_appointments_service_id', 'appointments', type_='foreignkey')
    # ### end Alembic commands ###
